dbclients={ 'PGRES':r"C:\Program Files\PostgreSQL\9.4\bin",
			'ORA11G':r'C:\app\alex_buz\product\11.2.0\dbhome_2\BIN',
			'ORAXE':r'C:\app\alex_buz\product\11.2.0\dbhome_2\BIN',
			#'ORA11G':r'C:\ORACLE\product\11.1.0\client_1\BIN',
			'ORAEXA':r'C:\app\alex_buz\product\11.2.0\dbhome_2\BIN',
			'SSENT':r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn',
			'SSEXP':r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn',
			'MYSQL':r'C:\Temp\mysql\bin',	'INFOB':r'C:\Temp\mysql\bin',	
			#'CSVFILE':r'', 'CSVDIR':r'', 
			'CSV':r'',
			'SYANY': r'C:\Program Files\SQL Anywhere 16\Bin64',
			'SYASE': r'C:\Program Files\SQL Anywhere 16\Bin64',
			'SYIQ': r'C:\Program Files\SQL Anywhere 16\Bin64',
			'TTEN':r'C:\Program Files (x86)\TimesTen\tt1122_64\bin',
			#'DBTUDB':r'C:\Program Files (x86)\IBM\SQLLIB_01\BIN',
			'INFOR':r'C:\Program Files (x86)\IBM Informix Software Bundle\bin',
			'INFORC':r'C:\Program Files (x86)\IBM Informix Software Bundle\bin',
			'MARIA':r'C:\Program Files\MariaDB 10.0\bin',
			'SLITE':'C:\Temp\SqlLite'}
mapping={'active_mapping': 'local_nt/20', 'local_host': 0,
 'host_list': {0: {'db_env': {'ORA11G': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                         'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
                              'ORAEXA': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                         'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
                              'ORAXE': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                        'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
							  'PGRES': {'source': r'C:\Program Files\PostgreSQL\9.4\bin',
							            'target': r'C:\Program Files\PostgreSQL\9.4\bin'},
                              'SSENT': {'source': r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn',
							            'target': r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn'},
                              'SSEXP': {'source': r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn',
							            'target': r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn'},
                              'MYSQL': {'source': r'C:\Temp\mysql\bin',
							            'target': r'C:\Temp\mysql\bin'},
                              'SYANY': {'source': r'C:\Program Files\SQL Anywhere 16\Bin64',
							            'target': r'C:\Program Files\SQL Anywhere 16\Bin64'},
                              'SYASE': {'source': r'C:\Program Files\SQL Anywhere 16\Bin64',
							            'target': r'C:\Program Files\SQL Anywhere 16\Bin64'},
                              'SYIQ': {'source': r'C:\Program Files\SQL Anywhere 16\Bin64',
							            'target': r'C:\Program Files\SQL Anywhere 16\Bin64'},
                              'TTEN': {'source': r'C:\Program Files (x86)\TimesTen\tt1122_64\bin',
							            'target': r'C:\Program Files (x86)\TimesTen\tt1122_64\bin'},
                              'INFOR': {'source': r'C:\Program Files (x86)\IBM Informix Software Bundle\bin',
							            'target': r'C:\Program Files (x86)\IBM Informix Software Bundle\bin'},
                              'INFORC': {'source': r'C:\Program Files (x86)\IBM Informix Software Bundle\bin',
							            'target': r'C:\Program Files (x86)\IBM Informix Software Bundle\bin'},
                              'MARIA': {'source': r'C:\Program Files\MariaDB 10.0\bin',
							            'target': r'C:\Program Files\MariaDB 10.0\bin'},
                              'SLITE': {'source': r'C:\Temp\SqlLite',
							            'target': 'C:\Temp\SqlLite'},
                              'INFOB': {'source': r'C:\Program Files\PostgreSQL\9.4\bin',
							            'target': r'C:\Program Files\PostgreSQL\9.4\bin'},
                              'DBTUDB': {'source': r'C:\Program Files\PostgreSQL\9.4\bin',
							            'target': r'C:\Program Files\PostgreSQL\9.4\bin'}
										},
                   'env': ['nt', None],
                   'login': ['localhost', None, None]},
               1: {'db_env': {'ORA11G': {'source': '/tmp/home/oracle/app/oracle/product/12.1.0/dbhome_1',
                                         'target': '/tmp/home/oracle/app/oracle/product/12.1.0/dbhome_1'}},
                   'env': ['posix', 'bash'],
                   'login': ['192.168.15.91', 'oracle', 'oracle']},
               2: {'env': ['posix', 'bash'],
                   'login': ['192.168.15.91', 'oracle', 'oracle']}},
 'host_map': {'dev_shards1': [{'host': 1, 'shards': '0:20'}],
              'local_nt/20': [{'host': 0, 'shards': '0:20'}],
              'threads': [{'host': 0, 'threads': '0:20'}]},
 'version': 2}


		
