echo y|dm.exe ^
-w csv2dbtudb ^
-o 1 ^
-r 1 ^
-t "|" ^
-i C:\Python27\datamule_1235\test\v101\data\db2_shard_0.data ^
-y 100 ^
-a ALEX_BUZ.Persons_pipe_datetime_1 ^
-u "ALEX_BUZ" ^
-p "test_pwd" ^
-d "SAMPLE" ^
-s "DB2" ^
-Z "C:\Program Files (x86)\IBM\SQLLIB_01\BIN"