mapping={'active_mapping': 'local_windows',
 'host_list': {0: {'db_env': {'CSV': {'source': '', 'target': ''},
                              'DBTAES': {'source': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN',
                                         'target': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN'},
                              'DBTAWS': {'source': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN',
                                         'target': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN'},
                              'DBTDE': {'source': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN',
                                        'target': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN'},
                              'DBTE': {'source': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN',
                                       'target': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN'},
                              'DBTEC': {'source': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN',
                                        'target': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN'},
                              'DBTES': {'source': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN',
                                        'target': 'C:\\Program Files (x86)\\IBM\\SQLLIB_01\\BIN'},
                              'DDL': {'source': '', 'target': ''},
                              'INFOB': {'source': 'C:\\Program Files\\PostgreSQL\\9.4\\bin',
                                        'target': 'C:\\Program Files\\PostgreSQL\\9.4\\bin'},
                              'INFOR': {'source': 'C:\\Program Files (x86)\\IBM Informix Software Bundle\\bin',
                                        'target': 'C:\\Program Files (x86)\\IBM Informix Software Bundle\\bin'},
                              'INFORC': {'source': 'C:\\Program Files (x86)\\IBM Informix Software Bundle\\bin',
                                         'target': 'C:\\Program Files (x86)\\IBM Informix Software Bundle\\bin'},
                              'JSON': {'source': '', 'target': ''},
                              'MARIA': {'source': 'C:\\Program Files\\MariaDB 10.0\\bin',
                                        'target': 'C:\\Program Files\\MariaDB 10.0\\bin'},
                              'MONGO': {'source': 'C:\\Program Files\\MongoDB\\Server\\3.0\\bin',
                                        'target': 'C:\\Program Files\\MongoDB\\Server\\3.0\\bin'},
                              'MYSQL': {'source': 'C:\\Temp\\mysql\\bin',
                                        'target': 'C:\\Temp\\mysql\\bin'},
                              'ORA11G': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                         'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
                              'ORA12C': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                         'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
                              'ORAEXA': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                         'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
                              'ORAXE': {'source': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN',
                                        'target': 'C:\\app\\alex_buz\\product\\11.2.0\\dbhome_2\\BIN'},
                              'PGRES': {'source': 'C:\\Program Files\\PostgreSQL\\9.4\\bin',
                                        'target': 'C:\\Program Files\\PostgreSQL\\9.4\\bin'},
                              'SLITE': {'source': 'C:\\Temp\\SqlLite',
                                        'target': 'C:\\Temp\\SqlLite'},
                              'SSENT': {'source': 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn',
                                        'target': 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn'},
                              'SSEXP': {'source': 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn',
                                        'target': 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\110\\Tools\\Binn'},
                              'SYANY': {'source': 'C:\\Program Files\\SQL Anywhere 16\\Bin64',
                                        'target': 'C:\\Program Files\\SQL Anywhere 16\\Bin64'},
                              'SYASE': {'source': 'C:\\Program Files\\SQL Anywhere 16\\Bin64',
                                        'target': 'C:\\Program Files\\SQL Anywhere 16\\Bin64'},
                              'SYIQ': {'source': 'C:\\Program Files\\SQL Anywhere 16\\Bin64',
                                       'target': 'C:\\Program Files\\SQL Anywhere 16\\Bin64'},
                              'TTEN': {'source': 'C:\\Program Files (x86)\\TimesTen\\tt1122_64\\bin',
                                       'target': 'C:\\Program Files (x86)\\TimesTen\\tt1122_64\\bin'}},
                   'env': ['nt', None],
                   'login': ['localhost', None, None]},
               1: {'db_env': {'ORA11G': {'source': '/tmp/home/oracle/app/oracle/product/12.1.0/dbhome_2',
                                         'target': '/tmp/home/oracle/app/oracle/product/12.1.0/dbhome_2'}},
                   'env': ['posix', 'bash'],
                   'login': ['192.168.15.91', 'oracle', 'oracle']},
               2: {'env': ['posix', 'bash'],
                   'login': ['192.168.15.91', 'oracle', 'oracle']}},
 'host_map': {'dev_linux': [{'host': 1, 'shards': '0:20'}],
              'local_windows': [{'host': 0, 'shards': '0:20'}]},
 'local_host': 0,
 'version': 2}
